<P> <img src="https://i.ibb.co/gyNf19D/nhslogo.png" alt="nhslogo" border="0" width="100" align="right"><font size="6"><b> CS4132 Data Analytics</b> </font>

# Lab 2.2: NumPy Array

## (Section 2.5) Manipulating an Array

Complete the following questions and upload your `.ipynb` file to Coursemology.

Name the file in the following format:

`Lab<Num><YourName>.ipynb`

Note that for each question, you should shortlist at least 3 non-trivial test cases to show the correctness of your solution.

### Q1

Create a function named `border()` which will

<ul>
<li><span lang="EN-GB">take in an argument&nbsp;<em>n&nbsp;</em>denoting the size of a 2D array</span></li>
<li><span lang="EN-GB">create a 2D array of shape&nbsp;<em>n</em>&nbsp;by&nbsp;<em>n</em>&nbsp;with 1 on the border and 0 inside</span></li>
<li><span lang="EN-GB">finally return the array created.</span></li>
</ul>
<p>For example, if&nbsp;<em>n</em>&nbsp;is 5, the following array will be returned:</p>
<pre>[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]</pre>

In [1]:
import numpy as np
#your solution
def border(n):
    arr = np.full((n, n), 0.)
    if n == 1:
        arr[0, 0] = 1.
        return arr
    arr[0:n:n - 1] = 1.
    arr[1:n - 1, 0:n:n - 1] = 1.
    return arr

Show how you test the correctness of your code below:

In [2]:
border(2)

array([[1., 1.],
       [1., 1.]])

In [3]:
border(1)

array([[1.]])

In [4]:
border(5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Q2

Create a function named `checkerBoard()` which will
<ul>
<li><span lang="EN-GB">take in an argument&nbsp;<em>n&nbsp;</em>denoting the size of a 2D array</span></li>
<li><span lang="EN-GB">create a 2D array of shape&nbsp;<em>n</em>&nbsp;by&nbsp;<em>n</em></span>&nbsp;with a checkerboard pattern.&nbsp;</li>
<li><span lang="EN-GB">finally return the array created.</span></li>
</ul>
<p>For example, if&nbsp;<em>n&nbsp;</em>is 8, the following array will be returned:</p>
<pre>[[0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0],<br /> [0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0],<br /> [0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0],<br /> [0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0]]</pre>

In [5]:
#your solution
def checkerboard(n):
    arr = np.full((n, n), 0)
    arr[0:n:2, 1:n + 1:2] = 1
    arr[1:n + 1:2, 0:n:2] = 1
    return arr

Show how you test the correctness of your code below:

In [6]:
checkerboard(5)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [7]:
checkerboard(8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [8]:
checkerboard(2)

array([[0, 1],
       [1, 0]])

### Q3

Create a function named `swap()` which will
<ul>
<li><span lang="EN-GB">take in 3 argument, <em>arr</em>,&nbsp;<em>a&nbsp;</em>and&nbsp;<em>b</em></span></li>
<li>it will then swap the contents of <span lang="EN-GB"><em>arr&nbsp;</em></span>in column <em>a</em> and column <em>b</em></li>
<li><span lang="EN-GB">finally return the updated array</span></li>
</ul>
<p>For example, given arr:</p>
<pre>[[ 0, 1,  2,  3],<br /> [ 4, 5,  6,  7],<br /> [ 8, 9,  10, 11],<br /> [12, 13, 14, 15]]</pre>
<p>Calling swap(arr,0,2) results in:</p>
<pre>[[ 2, 1,  0,  3],<br /> [ 6, 5,  4,  7],<br /> [10, 9,  8,  11],<br /> [14, 13, 12, 15]]</pre>

In [9]:
#your solution
def swap(arr, a, b):
    temp = arr[:, a].copy()
    arr[:, a] = arr[:, b].copy()
    arr[:, b] = temp
    return arr

Show how you test the correctness of your code below:

In [10]:
swap(border(5), 0, 2)

array([[1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
swap(border(10), 0, -1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
swap(border(5), 0, 3)

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Q4

Create a function named `slot()` which will
<ul>
<li><span lang="EN-GB">take in 3 arguments, a 3d array&nbsp;<em>arr</em>, integers&nbsp;<em>a&nbsp;</em>and&nbsp;<em>b</em></span></li>
<li>it will then copy the contents in sheet a and insert into position b</li>
<li><span lang="EN-GB">finally return the updated array</span></li>
</ul>
<p>For example, given arr:</p>
<pre>[[[11, 12],
 [13, 14]],

 [[21, 22],
 [23, 23]]]</pre>
<p>Calling slot(arr,1,0) results in:</p>
<pre>[[[21, 22],
  [23, 23]],

  [[11, 12],
  [13, 14]],
  
  [[21, 22],
  [23, 23]]]</pre>

In [13]:
#your solution
def slot(arr, a, b):
    return np.insert(arr, b,arr[a].copy(), axis=0)

Show how you test the correctness of your code below:

In [14]:
npa = np.array([[[11, 12],[13, 14]],[[21, 22],[23, 23]]])
slot(npa, 1, 0)

array([[[21, 22],
        [23, 23]],

       [[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 23]]])

In [15]:
npa2 = np.array([[[11, 12],[13, 14]],[[21, 22],[23, 23]]])
slot(npa2, 0, 0)

array([[[11, 12],
        [13, 14]],

       [[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 23]]])

In [16]:
npa2 = np.array([[[11, 12],[13, 14]],[[21, 22],[23, 23]]])
slot(npa2, 1, 1)

array([[[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 23]],

       [[21, 22],
        [23, 23]]])

### Q5

Create a function named `create3d()` which will
<ul>
<li><span lang="EN-GB">take in a integers <i>n</i></span></li>
<li>it will then create a 3d array of <em>n</em> by <em>n</em> by <em>n</em> with random integer values of range [1,99]</li>
<li><span lang="EN-GB">finally return the updated array</span></li>
</ul>
<p>For example, calling create3d(2) may result in:</p>
<pre>[[[ 5, 82],
  [15, 30]],

  [[ 1, 36],
   [65, 74]]]</pre>
<p>Calling create3d(3) may result in:</p>
<pre>[[[97, 21, 49],
  [70, 11, 63],
  [41, 57, 93]],

 [[75, 66, 27],
  [12, 28, 17],
  [65, 67, 82]],

 [[67, 97, 60],
  [72, 36, 24],
  [26, 82, 26]]]</pre>

In [17]:
#your solution
def create3d(n):
    arr = np.random.randint(low=1, high=100, size=(n, n, n))
    return arr

Show how you test the correctness of your code below:

In [18]:
create3d(4)

array([[[13, 76, 77,  1],
        [37, 45, 37, 55],
        [18, 29, 37, 79],
        [93,  1, 37, 27]],

       [[34, 42, 67, 34],
        [96, 82, 50, 88],
        [84, 92, 41, 17],
        [43, 89,  4, 36]],

       [[63, 52, 36, 88],
        [55, 13, 91, 16],
        [30, 34, 54, 89],
        [18, 21, 46, 51]],

       [[91, 93, 33,  7],
        [32, 96, 60,  9],
        [47, 21,  7, 65],
        [ 5, 41, 37,  6]]])

In [19]:
create3d(3)

array([[[89, 13, 19],
        [46, 37, 64],
        [ 5, 60,  4]],

       [[60, 37, 98],
        [40, 15, 28],
        [69, 61, 95]],

       [[69, 73, 41],
        [ 7, 59, 79],
        [64, 42, 38]]])

In [20]:
create3d(2)

array([[[16, 34],
        [23, 91]],

       [[62, 97],
        [71, 81]]])

### Q6

Create a function named `verticalStack()` which will
<ul>
<li>take in a 3d array from create3d() from question 5</li>
<li>it will then stack the sheets in the array from create3d() in reverse order, resulting in a 2d array.</li>
<li><span lang="EN-GB">finally return the 2d array</span></li>
</ul>
<p>For example, create3d(3) may result in:</p>
<pre>      [[[29, 32, 35],
        [89, 59, 77],
        [37, 87, 80]],

       [[75, 95, 39],
        [14, 79, 83],
        [67, 25, 31]],

       [[81, 61, 10],
        [35, 60,  3],
        [93, 17, 91]]]</pre>
<p>Calling verticalStack(create3d(3)) will result in:</p>
<pre>      [[81, 61, 10],
       [35, 60,  3],
       [93, 17, 91],
       [75, 95, 39],
       [14, 79, 83],
       [67, 25, 31],
       [29, 32, 35],
       [89, 59, 77],
       [37, 87, 80]]</pre>

In [21]:
#your solution
def verticalStack(arr):
    n = arr.shape[0]
    arr2 = arr[::-1].reshape((n * n, n))
    return arr2

Show how you test the correctness of your code below:

In [22]:
a = create3d(3)
print(a)
print(verticalStack(a))

[[[32 85 92]
  [62 68 35]
  [58 54 69]]

 [[87 45 55]
  [38 52 16]
  [72 36 60]]

 [[51 85 37]
  [ 4  6 89]
  [52 35 28]]]
[[51 85 37]
 [ 4  6 89]
 [52 35 28]
 [87 45 55]
 [38 52 16]
 [72 36 60]
 [32 85 92]
 [62 68 35]
 [58 54 69]]


In [23]:
b = create3d(2)
print(b)
print(verticalStack(b))

[[[15 69]
  [33 11]]

 [[84 82]
  [78 74]]]
[[84 82]
 [78 74]
 [15 69]
 [33 11]]


In [24]:
c = create3d(4)
print(c)
print(verticalStack(c))

[[[26 76 37 26]
  [92 64 12 36]
  [97 73 16 82]
  [ 5  1 29 17]]

 [[71 93 86 49]
  [48 91 97  3]
  [22 52 96 49]
  [87 21 10 34]]

 [[84 39 23 90]
  [83  4 53 15]
  [13 61 33 68]
  [72 55 72 58]]

 [[31 27 55 11]
  [68 40 57 99]
  [18 55 32 71]
  [ 6 45 23 46]]]
[[31 27 55 11]
 [68 40 57 99]
 [18 55 32 71]
 [ 6 45 23 46]
 [84 39 23 90]
 [83  4 53 15]
 [13 61 33 68]
 [72 55 72 58]
 [71 93 86 49]
 [48 91 97  3]
 [22 52 96 49]
 [87 21 10 34]
 [26 76 37 26]
 [92 64 12 36]
 [97 73 16 82]
 [ 5  1 29 17]]


### Q7

Create a function name `findGreater()` which will take in an input array and integer n, and return elements which are greater than n as a 1D array.

In [25]:
#your solution
def findGreater(arr, n):
    lists = arr.flatten().tolist()
    arr2 = np.array([i for i in lists if i > n])
    return arr2


Show how you test the correctness of your code below:

In [26]:
a = create3d(2)
print(a)
print(findGreater(a, 40))

[[[ 1 60]
  [52 42]]

 [[84 45]
  [93 30]]]
[60 52 42 84 45 93]


In [27]:
b = create3d(3)
print(b)
print(findGreater(b, 60))

[[[55 80 72]
  [27 82 67]
  [89 72 60]]

 [[30 67 80]
  [51 28 71]
  [23 67 12]]

 [[55 24 84]
  [21  3 41]
  [39 67 59]]]
[80 72 82 67 89 72 67 80 71 67 84 67]


In [28]:
c = create3d(4)
print(c)
print(findGreater(c, 20))

[[[31 73 12 50]
  [96  6 73 53]
  [ 4 29 50 15]
  [82 29 89 30]]

 [[89 75 25 74]
  [13 99 10 66]
  [ 4 94 56 20]
  [37 39 47  4]]

 [[27 69 15  6]
  [70 25 27 77]
  [47 88  5 47]
  [46 29  6 66]]

 [[84 12 55 25]
  [41 84  3 81]
  [26 90  8 90]
  [38 78 18 50]]]
[31 73 50 96 73 53 29 50 82 29 89 30 89 75 25 74 99 66 94 56 37 39 47 27
 69 70 25 27 77 47 88 47 46 29 66 84 55 25 41 84 81 26 90 90 38 78 50]
