<P> <img src="https://i.ibb.co/gyNf19D/nhslogo.png" alt="nhslogo" border="0" width="100" align="right"><font size="6"><b> CS4132 Data Analytics</b> </font>

# Lab 2.1: NumPy Array

### Submission Instructions

* Complete the following questions and upload your `.ipynb` file to Coursemology.
* Name the file in the following format: `Lab<num><YourName>.ipynb`
* Before submitting, please ensure you click on "Kernel" > "Restart and Run All" on your jupyter notebook. 
* Finally, print a copy of your final solution to OneNote > Your Individual Student Notebook > Labs. Name the page `Lab <num>`.

## Section (2.1 and 2.2) Array Creation & Attributes

In [2]:
import numpy as np

### Q1

Create a 1d array using the following list: `[12.23, 13.32, 100, 36.32]`

In [2]:
np.array([12.23, 13.32, 100, 36.32])

array([ 12.23,  13.32, 100.  ,  36.32])

### Q2

Create a 1d array consisting of even numbers from 20 to 100, inclusive of both.

In [4]:
np.arange(20, 101, 2)

array([ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38,  40,  42,  44,
        46,  48,  50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,
        72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,
        98, 100])

### Q3

Create a 3d array of 4 sheets, 3 rows and 5 columns consisting of data 1,2,3,4,5.

In [6]:
np.array([[[1, 2, 3, 4, 5]]*3]*4)

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

### Q4

Create a 6 by 7 array filled with 9.

In [7]:
np.full((6, 7), 9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

### Q5

Create an array consisting of 20 evenly-spaced points on the interval [5, 10]

In [8]:
np.linspace(5, 10, 20)

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

### Q6

Create a 1d array of 30 random integer in range [-50, 20].

In [9]:
np.random.randint(low=-50, high=21, size=30)

array([ -3, -46, -27, -44, -32, -31, -44, -19, -33, -28, -49,  17, -18,
        -6,  11, -37, -21,  17,  -8,  -6, -23, -26, -47, -25,   4, -24,
       -24, -31, -39, -47])

## (Section 2.3) Array Indexing & Slicing

### Q7

Write relevant code to access the following elements in the array below.

In [17]:
import numpy as np
x1 = np.arange(23,87,5)
x1

array([23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83])

In [11]:
#get the 1st value in the array
x1[0]

23

In [12]:
#get the fifth value in the array
x1[4]

43

In [13]:
#get the last value in the array
x1[-1]

83

In [15]:
#get the second last value in the array
x1[-2]

78

### Q8

Write relevant code to access the following elements in the array below.

In [53]:
x2 = np.array([[3, 7, 5, -5], [12, 1, 2, 9], [3, 0, 8, 10]])
x2

array([[ 3,  7,  5, -5],
       [12,  1,  2,  9],
       [ 3,  0,  8, 10]])

First row refers to [ 3,  7,  5, -5]

In [17]:
#get the 1st row and 2nd column value
x2[0, 1]

7

In [18]:
#get the 3rd row, last value
x2[2, -1]

10

In [54]:
#Retrieve the elements in first and 3rd column
x2[:, 0:3:2]

array([[ 3,  5],
       [12,  2],
       [ 3,  8]])

In [23]:
#Retrieve the elements at the 4 corners (i.e. 3, )
x2[0:3:2, 0:4:3]

array([[ 3, -5],
       [ 3, 10]])

In [26]:
#update value of -9 to the first element in the first row, first column
x2[0, 0] = -9
x2

array([[-9,  7,  5, -5],
       [12,  1,  2,  9],
       [ 3,  0,  8, 10]])

### Q9

Write relevant code to slice the following elements in the array below.

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#slice from 4th value to 6th value (inclusive of both)
x[3:6]

array([3, 4, 5])

In [30]:
#return elements at even indexed position
x[::2]

array([0, 2, 4, 6, 8])

In [32]:
#return elements from 2nd value step by 3
x[1::3]

array([1, 4, 7])

In [33]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Q10

Write relevant code to access/slice the following elements in the array below.

In [34]:
x = np.array([[[ 0,  1,  2],
               [ 3,  4,  5]],

              [[ 6,  7,  8],
               [ 9, 10, 11]],

              [[12, 13, 14],
               [15, 16, 17]]])
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [36]:
#access the element on 1st row, 2nd column of last sheet
x[2, 0, 1]

13

In [37]:
#retrieve the last element of each row of each sheet
x[:, :, -1]

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [38]:
#find the shape of the array above
x[:, :, -1].shape

(3, 2)

In [39]:
#retrieve the 2nd row of every sheet
x[:, 1]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])

In [41]:
#retrieve the last element of each sheet
x[:, -1, -1]

array([ 5, 11, 17])

## (Section 2.4) Operations on NumPy

### Q11

Use the numpy array created below to answer the questions below.

In [19]:
import numpy as np
data = np.array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

Find the average value of the second column (to two decimal places).

In [20]:
print("%.2f"%np.mean(data[:, 1]))

214895.80


Find the average value of the first 5 rows of the third and fourth columns.

In [21]:
np.mean(data[:6, 2:4])

282201.8333333333

Find the median value of the last column.

In [23]:
np.median(data[:,-1])

237483.0

Find the sum of all values in the array.

In [24]:
data.sum()

23526182

Find the minimum value in the array.

In [25]:
data.min()

3975

Find the sum of the first and last column. Then multiply each element by 5.

In [26]:
(data[:, 0] + data[:, -1]) * 5

array([ 814055, 1202980, 2575040,  272180, 2555370, 2878890, 1243675,
       3358720, 4349700, 1999155, 3764090, 1961045, 3715955, 2191645,
       2089885, 2619210, 1278000, 1573500, 1824420, 2531795])

Find the sum of all even rows.

In [27]:
data[::2].sum()

12387254

### Q12

Using the concept of array broadcasting, create a 2d array for 5 by 5 multiplication table.

In [78]:
np.array([1, 2, 3, 4, 5]) * np.array([[1], [2], [3], [4], [5]])

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Q13

You are given 2 lists containing the weight (in kg) and height (in m) of 20 individuals.

Calculate their BMI and store it in a 1d array.

BMI Formula: weight (kg) / [height (m)]^2

In [80]:
weight = [57, 54, 21, 54, 42, 44, 26, 30, 34, 44, 31, 39, 44, 28, 40, 58, 40, 24, 47, 57]
height = [1.22, 1.63, 1.74, 1.65, 1.73, 1.79, 1.72, 1.31, 1.76, 1.01, 1.36, 1.17, 1.11, 1.  , 1.56, 1.12, 1.35, 1.05, 1.23, 1.09]

In [83]:
np.array(weight) / (np.array(height) * np.array(height))

array([38.29615695, 20.32443826,  6.93618708, 19.83471074, 14.03321193,
       13.73240536,  8.78853434, 17.48149875, 10.97623967, 43.13302617,
       16.76038062, 28.49002849, 35.71138706, 28.        , 16.4365549 ,
       46.2372449 , 21.9478738 , 21.76870748, 31.06616432, 47.97575962])

### Q14

You are given a list containing temperature in celsius. 

Convert the data into fahrenheit and store it in a 1d array.

Formula: °F = (°C ×  9 / 5 ) + 32 

In [86]:
celsius = [39.5, 21.8, 34.5, 25.1, 16.4, 15.8, 26.7, 31.6, 15.6, 21.8, 13.7, 48.7, 13.8, 46.1, 25.3, 43.4, 35.2, 19.4, 18.6, 16.3, 20.8, 15.9, 42. , 14.9, 20.6, 18.9, 30. , 12.9, 44. , 49.6]

In [87]:
(np.array(celsius) * (9/5)) + 32

array([103.1 ,  71.24,  94.1 ,  77.18,  61.52,  60.44,  80.06,  88.88,
        60.08,  71.24,  56.66, 119.66,  56.84, 114.98,  77.54, 110.12,
        95.36,  66.92,  65.48,  61.34,  69.44,  60.62, 107.6 ,  58.82,
        69.08,  66.02,  86.  ,  55.22, 111.2 , 121.28])

### Q15

The quiz scores of class A and class B is given in the 3d array below.

Each class has 20 students, and there are a total of 3 quizzes.

In [3]:
scores = np.array([[[91, 55, 84],
                    [69, 12, 70],
                    [84, 75, 33],
                    [21, 91,  2],
                    [12, 60, 40],
                    [42, 91, 51],
                    [26, 47, 85],
                    [ 8, 21, 73],
                    [85, 12, 22],
                    [ 2, 79, 73],
                    [57, 74, 20],
                    [23, 98, 82],
                    [23, 73, 33],
                    [58, 81, 71],
                    [66, 74, 12],
                    [85, 16, 68],
                    [44, 26,  5],
                    [15, 13, 32],
                    [86, 67,  1],
                    [66,  8, 34]],

                   [[40, 37, 15],
                    [53, 73, 64],
                    [73, 90, 10],
                    [95, 94, 32],
                    [46, 20, 44],
                    [12, 86, 24],
                    [17, 20, 15],
                    [87, 51,  5],
                    [63, 82,  2],
                    [66,  9, 29],
                    [59, 24, 32],
                    [43, 43, 65],
                    [62,  6, 86],
                    [92, 29,  7],
                    [47, 76, 15],
                    [46, 56, 70],
                    [74, 80, 50],
                    [42, 91, 14],
                    [92, 13, 17],
                    [76,  2, 54]]])

Find the average of each quiz for each class.

In [9]:
np.mean(scores, axis=1)

array([[48.15, 53.65, 44.55],
       [59.25, 49.1 , 32.5 ]])

Find the average of quiz score of each student in class B.

In [28]:
np.mean(scores[1], axis=1)

array([30.66666667, 63.33333333, 57.66666667, 73.66666667, 36.66666667,
       40.66666667, 17.33333333, 47.66666667, 49.        , 34.66666667,
       38.33333333, 50.33333333, 51.33333333, 42.66666667, 46.        ,
       57.33333333, 68.        , 49.        , 40.66666667, 44.        ])

Find the max scorer for quiz 3 for the respective classes.

In [108]:
np.max(scores[:, :, 2], axis=1)

array([85, 86])

Find the median score for quiz 2 for each class.

In [105]:
np.median(scores[:, :, 1], axis=1)

array([63.5, 47. ])